"""create_table_conversation_context_table

Revision ID: a4d1a1181a49
Revises: 914495013e7e
Create Date: 2025-12-09 21:14:34.769543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d1a1181a49'
down_revision: Union[str, None] = '914495013e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_contexts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('word', sa.String(length=255), nullable=False),
                    sa.Column('language', sa.String(length=50), nullable=False),
                    sa.Column('native_language', sa.String(length=50), nullable=False),
                    sa.Column('context_hash', sa.String(length=64), nullable=False),
                    sa.Column('messages', sa.Text(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('context_hash')
                    )
    op.create_index(op.f('ix_conversation_contexts_context_hash'), 'conversation_contexts', ['context_hash'],
                    unique=False)
    op.create_index(op.f('ix_conversation_contexts_user_id'), 'conversation_contexts', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_contexts_word'), 'conversation_contexts', ['word'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_conversation_contexts_word'), table_name='conversation_contexts')
    op.drop_index(op.f('ix_conversation_contexts_user_id'), table_name='conversation_contexts')
    op.drop_index(op.f('ix_conversation_contexts_context_hash'), table_name='conversation_contexts')
    op.drop_table('conversation_contexts')
